### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by lorvent** [dtbaker/dashboard-plus#36]
hi dtbaker

dashboard plus not working for almost 15days

**Comment by dtbaker** [comment]
Try clicking on  your settings page, then go to "Badges" menu on the left, then scroll down to the very bottom and see if a new menu item called "Dashboard Plus" appears.

**Comment by lorvent** [comment]
hmm crazy, its working.

i am using it for almost 2years and suddenly my settings gone or an caused it to reset settings?
