### ISSUE TITLE
Doesn't work on latest update from Envato

### ISSUE THREAD

**Issue by thongta** [dtbaker/dashboard-plus#40]
Hi,

You might be noticed that your awesome Chrome extension is no longer working on the latest update from Envato.

Looking forward to your update.

**Comment by Ninetheme** [comment]
and we're, i check on chrome and there is null iframe bottom of page.

**Comment by ryanlabelle** [comment]
This appears to be working for me after updating to the most recent version and reloading extensions. Thanks!
