### ISSUE TITLE
Not working after new envato update

### ISSUE THREAD

**Issue by Ninetheme** [dtbaker/dashboard-plus#46]
Thank you

**Comment by Ninetheme** [comment]
@dtbaker @revaxarts

**Comment by revaxarts** [comment]
"Not working" is not very helpful. Please use a better wording and describe _what exactly_ is actually not working!

**Comment by Ninetheme** [comment]
But if a thing not working we can say just not working :) Not working dashboard plus extension ? Thank you, i haven't details.
